extraction:
  cpp:
    after_prepare:
      - mkdir -p _lgtm_build_dir/CMakeFiles/git-data
      - echo "lgtm-build-no-sha" > _lgtm_build_dir/CMakeFiles/git-data/head-ref
    configure:
      command:
        - cd _lgtm_build_dir
        - cmake ..
